/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Bliksem                                               *
* Dimensions:  48 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBliksem;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsBliksem[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalBliksem = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acBliksem[] = {
  XX______, ________, _____XX_, ________, ________, ________,
  _XXX____, ________, _____XXX, X_______, ________, ________,
  __XXXX__, ________, _____XXX, XXXX____, ________, ________,
  ___XXXXX, ________, _____XXX, XXXXXX__, ________, ________,
  ____XXXX, XX______, _____XXX, XXXXXXXX, X_______, ________,
  _____XXX, XXXX____, _____XXX, XXXXXXXX, XXX_____, ________,
  ______XX, XXXXXX__, _____XXX, XXXXXXXX, XXXXXX__, ________,
  _______X, XXXXXXXX, _____XXX, XXXXXXXX, XXXXXXXX, ________,
  ________, XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXXX, XXX_____,
  ________, _XXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, XXXXX___,
  ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ________, __XXXXXX, XXXXXXX_, XXXXXXXX, XXXXXXXX,
  ________, ________, ___XXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  ________, ________, ____XXXX, XXXXXXX_, ___XXXXX, XXXXXXXX,
  ________, ________, _____XXX, XXXXXXX_, _____XXX, XXXXXXXX,
  ________, ________, ______XX, XXXXXXX_, ______XX, XXXXXXXX,
  ________, ________, _______X, XXXXXXX_, _______X, XXXXXXXX,
  ________, ________, ________, XXXXXXX_, ________, _XXXXXXX,
  ________, ________, ________, _XXXXXX_, ________, __XXXXXX,
  ________, ________, ________, __XXXXX_, ________, ____XXXX,
  ________, ________, ________, ___XXXX_, ________, _____XXX,
  ________, ________, ________, ____XXX_, ________, ______XX,
  ________, ________, ________, _____XX_, ________, ________,
  ________, ________, ________, ______X_, ________, ________,
  ________, ________, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmBliksem = {
  48, // xSize
  32, // ySize
  6, // BytesPerLine
  1, // BitsPerPixel
  _acBliksem,  // Pointer to picture data (indices)
  &_PalBliksem   // Pointer to palette
};

static GUI_CONST_STORAGE unsigned char _acBliksemSmall[] = {
  XX______, __XX____, ________,
  _XXX____, __XXXXX_, ________,
  __XXXX__, __XXXXXX, X_______,
  ___XXXXX, __XXXXXX, XXXX____,
  ____XXXX, XXXXXXXX, XXXXXX__,
  _____XXX, XXXXXXXX, XXXXXXXX,
  ______XX, XXXXXXXX, XXXXXXXX,
  _______X, XXXXXXXX, XXXXXXXX,
  ________, XXXXXXXX, XXXXXXXX,
  ________, _XXXXXXX, XXXXXXXX,
  ________, __XXXXXX, __XXXXXX,
  ________, ___XXXXX, ___XXXXX,
  ________, ____XXXX, _____XXX,
  ________, _____XXX, ______XX,
  ________, ______XX, _______X,
  ________, _______X, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmBliksemSmall = {
  24, // xSize
  16, // ySize
  3, // BytesPerLine
  1, // BitsPerPixel
  _acBliksemSmall,  // Pointer to picture data (indices)
  &_PalBliksem   // Pointer to palette
};

/*************************** End of file ****************************/
