/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.28.                           *
*        Compiled Jan 30 2015, 16:40:04                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Bliksem                                               *
* Dimensions:  48 * 32                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBattery;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsBliksem[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalIcon = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acBattery[] = {
	_XXXXXXX,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_X_____X,
	_XXX_XXX,
	___XXX__,
	________
};

GUI_CONST_STORAGE GUI_BITMAP bmBattery = {
  8, // xSize
  18, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acBattery,  // Pointer to picture data (indices)
  &_PalIcon   // Pointer to palette
};


static GUI_CONST_STORAGE unsigned char _acLightning[] = {
	XX__XX__,
	_XXXXXXX,
	__XXXXXX,
	___XX_XX,
	____X___,
};

GUI_CONST_STORAGE GUI_BITMAP bmLightning = {
  8, // xSize
  5, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acLightning,  // Pointer to picture data (indices)
  &_PalIcon   // Pointer to palette
};

static GUI_CONST_STORAGE unsigned char _acTimeLapse[] = {
	________,
	__X_____,
	_XXX____,
	_XXXXXXX,
	_XXXXXXX,
	__XXXXX_,
	___XXX__,
	________
};

GUI_CONST_STORAGE GUI_BITMAP bmTimeLapse = {
  8, // xSize
  8, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acTimeLapse,  // Pointer to picture data (indices)
  &_PalIcon   // Pointer to palette
};

static GUI_CONST_STORAGE unsigned char _acClock[] = {
	___XXX__,
	__X___X_,
	_X_____X,
	_X__XX_X,
	_X__X__X,
	__X___X_,
	___XXX__,
	________
};

GUI_CONST_STORAGE GUI_BITMAP bmClock = {
  8, // xSize
  8, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acTimeLapse,  // Pointer to picture data (indices)
  &_PalIcon   // Pointer to palette
};

static GUI_CONST_STORAGE unsigned char _acExternal[] = {
	___X____,
	__X__X__,
	_X____X_,
	_X_XXXXX,
	_X____X_,
	__X__X__,
	___X____,
	________
};

GUI_CONST_STORAGE GUI_BITMAP bmExternal = {
  8, // xSize
  8, // ySize
  1, // BytesPerLine
  1, // BitsPerPixel
  _acTimeLapse,  // Pointer to picture data (indices)
  &_PalIcon   // Pointer to palette
};

/*************************** End of file ****************************/
